ARG NODE_VERSION="lts"
FROM node:$NODE_VERSION

LABEL name="Expo for Docker"
LABEL repository="https://github.com/bycedric/expo-cli-images"
LABEL homepage="https://github.com/bycedric/expo-cli-images"
LABEL maintainer="Cedric van Putten <me@bycedric.com>"

ARG EXPO_VERSION="latest"

RUN apk add --no-cache bash git vips vips-dev build-base \
  && npm install --global --unsafe-perm sharp-cli expo-cli@$EXPO_VERSION \
  && npm cache clean --force \
  && apk del vips-dev build-base \
  && rm -rf /var/cache/apk/*

COPY entrypoint.sh LICENSE.md README.md /

ENTRYPOINT ["/entrypoint.sh"]
CMD ["--help"]
